### ISSUE TITLE
Models are not getting recognized

### ISSUE THREAD

**Issue by alexthewilde** [ForestAdmin/forest-loopback#7]
Forest can connect to the loopback server but it doesn't parse the models.

**Comment by arnaudbesnier** [comment]
Hey @alexthewilde, the Forest Loopback liana is not currently supported.
Sorry for that, if you really need an admin, you can use http://www.forestadmin.com/lumber instead.

**Comment by alexthewilde** [comment]
@arnaudbesnier if loopback is no longer supported, don't you think this repo should be closed then?

Lumber doesn't support MongoDB afaik, so it's no alternative either.

**Comment by arnaudbesnier** [comment]
My bad sorry for the quick response, you're totally right MongoDB is not supported by Lumber...
When I say that Forest Loopback is not currently supported, I mean by the Forest core team.
But as the liana is open-source, anyone can implement a feature or fix a bug.
